version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/html
    depends_on:
    - db
    dns:
    - 8.8.8.8
    - 8.8.4.4

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8081:80"  # Убедись, что порт 8081 свободен на твоем компьютере
    environment:
      PMA_HOST: db  # Имя сервиса MySQL, к которому нужно подключиться
      PMA_PORT: 3306
    depends_on:
    - db
volumes:
  db_data:
